language: ruby
sudo: false
before_script:
  - bundle update
cache: bundler
rvm:
  - 1.8.7-p374
  - 1.9.2-p330
  - 1.9.3-p551
  - 2.0.0-p648
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-9.0.5.0
  - jruby-head
  - rbx-2
  - rbx-3
  - ree
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
